#!/usr/bin/env bash
# Assemble apps/playground/public/ for local dev or Cloudflare deploy.
#
# Usage (from repo root):
#   apps/playground/build.sh
#   MODEL_URL=https://pub-xxx.r2.dev/akshar_wasm.model apps/playground/build.sh
#
# Layout (vendor/ mirrors the old repo tree so the wrapper's relative
# '../wasm/pkg' import resolves with zero wrapper changes):
#   public/index.html            the playground shell
#   public/config.js             GENERATED: { modelUrl }
#   public/vendor/js/akshar-ime.js        <- packages/engine-js/
#   public/vendor/wasm/pkg/*             <- packages/engine-wasm/pkg/
#   public/models/akshar_wasm.model       <- data/ (local dev only, gitignored;
#                                          deploys serve the model from R2)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PUB="$ROOT/apps/playground/public"
MODEL_URL="${MODEL_URL:-./models/akshar_wasm.model}"
MODEL_SRC="${MODEL_SRC:-$ROOT/data/akshar_wasm.model}"

mkdir -p "$PUB/vendor/js" "$PUB/vendor/wasm" "$PUB/models"
cp "$ROOT/packages/engine-js/akshar-ime.js" "$PUB/vendor/js/"
rm -rf "$PUB/vendor/wasm/pkg"
cp -r "$ROOT/packages/engine-wasm/pkg" "$PUB/vendor/wasm/pkg"
cat > "$PUB/config.js" <<EOF
// GENERATED by apps/playground/build.sh — do not edit (gitignored).
// Deploy override: MODEL_URL=<r2-public-url> apps/playground/build.sh
export const AKSHAR_CONFIG = { modelUrl: "$MODEL_URL" };
EOF

if [ -f "$MODEL_SRC" ]; then
  cp "$MODEL_SRC" "$PUB/models/akshar_wasm.model"
  echo ">> model: $MODEL_SRC -> public/models/ ($(du -h "$PUB/models/akshar_wasm.model" | cut -f1))"
else
  echo ">> no local model at $MODEL_SRC — skipping models/ copy"
  echo "   (deploy path serves the model from R2 via MODEL_URL)"
fi
echo ">> playground ready: $PUB (modelUrl=$MODEL_URL)"
